matrix:
  include:
    - os: linux
      sudo: required
      language: php
      php: 7.1
      addons:
        apt:
          packages:
            - npm
      before_install:
        - mkdir -p project
        - mv tests project
        - find "." -maxdepth 1 -not -type d -exec mv -t "project" -- '{}' +
    - os: osx
      osx_image: xcode9.3beta
      language: objective-c
      before_install:
        - brew update
        - brew tap homebrew/php
        - brew install composer
        - brew install node
        - mkdir -p project
        - mv tests project
        - find "." -maxdepth 1 -not -type d -exec mv -t "project" -- '{}' +
script:
  - cd project
  - composer install --optimize-autoloader --no-suggest
  - ./vendor/bin/phpunit