language: php

matrix:
  include:
    - os: windows
      name: windows (7.2.15)
      language: sh
      before_install:
        - choco install -y nodejs
        - choco install php -y --version 7.2.15 --package-parameters='"/InstallDir:C:\php"'
        - export PATH=/c/php:/c/composer:$PATH
        - sed -i 's/;extension=openssl/extension=openssl/g' /c/php/php.ini
        - sed -i 's/;extension=mbstring/extension=mbstring/g' /c/php/php.ini
        - mkdir /c/composer
        - wget -O /c/composer/composer.phar http://getcomposer.org/composer.phar
        - echo "@echo off" > /c/composer/composer.bat
        - echo "" >> /c/composer/composer.bat
        - echo "php c:\\composer\\composer.phar %*" >> /c/composer/composer.bat
        - cat /c/composer/composer.bat
        - echo "#!/bin/sh" > /c/composer/composer
        - echo 'php /c/composer/composer.phar "$@"' >> /c/composer/composer
        - chmod +x /c/composer/composer
        - cat  /c/composer/composer
      script: |
        if [ ! -f /tmp/test/vendor/bin/yarn.bat ]; then
          echo "yarn.bat doesn't exist in bin"
          exit 1
        fi
        if [ ! -f /tmp/test/vendor/bin/yarnpkg.bat ]; then
          echo "yarnpkg.bat doesn't exist in bin"
          exit 1
        fi
    - os: linux
      name: linux (7.1)
      php: 7.1
      addons:
        apt:
          packages:
            - nodejs
      script: |
        if [ ! -x /tmp/test/vendor/bin/yarn ]; then
          echo "yarn doesn't exist in bin"
          exit 1
        fi
        if [ ! -x /tmp/test/vendor/bin/yarnpkg ]; then
          echo "yarnpkg doesn't exist in bin"
          exit 1
        fi
    - os: linux
      name: linux (7.2)
      php: 7.2
      addons:
        apt:
          packages:
            - nodejs
      script: |
        if [ ! -x /tmp/test/vendor/bin/yarn ]; then
          echo "yarn doesn't exist in bin"
          exit 1
        fi
        if [ ! -x /tmp/test/vendor/bin/yarnpkg ]; then
          echo "yarnpkg doesn't exist in bin"
          exit 1
        fi
    - os: linux
      name: linux (7.3)
      php: 7.3
      addons:
        apt:
          packages:
            - nodejs
      script: |
        if [ ! -x /tmp/test/vendor/bin/yarn ]; then
          echo "yarn doesn't exist in bin"
          exit 1
        fi
        if [ ! -x /tmp/test/vendor/bin/yarnpkg ]; then
          echo "yarnpkg doesn't exist in bin"
          exit 1
        fi
    - os: osx
      name: osx
      osx_image: xcode9.4
      language: objective-c
      before_install:
        - brew uninstall --force node
        - brew cleanup
        - rm -rf ~/.npm /usr/local/bin/npm /usr/local/lib/dtrace/node.d
        - brew update
        - brew tap homebrew/core
        - brew install composer node
      script: |
        if [ ! -x /tmp/test/vendor/bin/yarn ]; then
          echo "yarn doesn't exist in bin"
          exit 1
        fi
        if [ ! -x /tmp/test/vendor/bin/yarnpkg ]; then
          echo "yarnpkg doesn't exist in bin"
          exit 1
        fi

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer -V

before_script:
  - cd /tmp
  - mkdir test
  - cd test
  - composer init --name=test/test --description="Just a test package" --author="Test <someone@somewhere.somehow>" --type=project --homepage=http://impresscms.org --license=MIT --stability=dev --require="imponeer/composer-yarn-installer=*" -q
  - composer install --no-dev