os:
  - linux
  - osx
addons:
  apt:
    packages:
      - npm
      - composer
osx_image: xcode9.3beta
language: c
stages:
  - download_composer_packages
  - create_test_dirs
  - before_tests
  - test_1
  - test_2
  - test_3
  - test_4
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew tap homebrew/php
      brew install composer
    fi
jobs:
  include:
    - stage: before_tests
      script: export PHPUNIT_PATH=$PWD/vendor/bin/phpunit $PWD/tests/InstalationTest.php
    - stage: download_composer_packages
      script: composer install --optimize-autoloader --no-suggest -v
    - stage: create_test_dirs
      script:
        - export temp=$(mktemp -d)
        - mkdir $temp/install-local
        - mkdir $temp/install-global
        - mkdir $temp/only-update-local
        - mkdir $temp/only-update-global
        - php -r "echo str_replace('\"%SRC_PATH%\"', json_encode(getcwd()), file_get_contents('tests/data/global.json'));" > $temp/install-global/composer.json
        - php -r "echo str_replace('\"%SRC_PATH%\"', json_encode(getcwd()), file_get_contents('tests/data/local.json'));" > $temp/install-local/composer.json
        - cat $temp/install-global/composer.json > $temp/only-update-global/composer.json
        - cat $temp/install-local/composer.json > $temp/only-update-local/composer.json
    - stage: test_1
      script: |
        pushd $temp/install-local
        ls -a
        composer install --no-dev --optimize-autoloader --no-suggest --no-interaction
        eval $PHPUNIT_PATH
        composer update --no-dev --optimize-autoloader --no-suggest --no-interaction
        eval $PHPUNIT_PATH
        popd
    - stage: test_2
      script: |
        pushd $temp/install-global
        ls -a
        composer install --no-dev --optimize-autoloader --no-suggest --no-interaction
        eval $PHPUNIT_PATH
        composer update --no-dev --optimize-autoloader --no-suggest --no-interaction
        eval $PHPUNIT_PATH
        popd
    - stage: test_3
      script: |
        pushd $temp/only-update-local
        ls -a
        composer update --no-dev --optimize-autoloader --no-suggest --no-interaction
        eval $PHPUNIT_PATH
        popd
    - stage: test_4
      script: |
        pushd $temp/only-update-global
        ls -a
        composer update --no-dev --optimize-autoloader --no-suggest --no-interaction
        eval $PHPUNIT_PATH
        popd