matrix:
  include:
    - os: linux
      sudo: required
      language: php
      php: 7.1
      addons:
        apt:
          packages:
            - npm
    - os: osx
      osx_image: xcode9.3beta
      language: objective-c
      before_install:
        - brew update
        - brew tap homebrew/php
        - brew install composer
script:
  - composer install --optimize-autoloader --no-suggest -v
  - ./vendor/bin/phpunit -v --debug