language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - npm
    - os: linux
      addons:
        apt:
          packages:
            - npm
            - yarn
    - os: linux
      addons:
        apt:
          packages:
            - yarn
    - os: linux
    - os: osx
      install:
        - brew update
        - brew tap homebrew/php
        - brew install composer
    - os: osx
      install:
        - brew update
        - brew tap homebrew/php
        - brew install composer npm
    - os: osx
      install:
        - brew update
        - brew tap homebrew/php
        - brew install composer npm yarn
    - os: osx
      install:
        - brew update
        - brew tap homebrew/php
        - brew install composer yarn
    - os: windows
      install:
        - choco install -y composer
    - os: windows
      install:
        - choco install -y composer npm
    - os: windows
      install:
        - choco install -y composer npm yarn
    - os: windows
      install:
        - choco install -y composer yarn

cache:
  directories:
    - $HOME/.composer/cache/files
script:
  - composer install --optimize-autoloader --no-suggest -v