matrix:
  include:
    - os: linux
      sudo: required
      language: php
      php: 7.1
      addons:
        apt:
          packages:
            - npm
      before_install:
        - mkdir -p /tmp
        - chmod 0777 /tmp
    - os: osx
      osx_image: xcode9.3beta
      language: objective-c
      before_install:
        - brew update
        - brew tap homebrew/php
        - brew install composer
        - mkdir -p /tmp
        - chmod 0777 /tmp
script:
  - composer install --optimize-autoloader --no-suggest
  - ./vendor/bin/phpunit